### PR TITLE
change the type of generalBracket, fixes #63

### LINKED ISSUE #63: regression: state updates performed while releasing are discarded
Commit 7ec3240eabc246b38ff0dc24af0be4535d7b57cf says:

> we are now forced to perform some discarding of updated state and Monoid written values in the StateT, WriterT, and RWST instances. This seems inherent to making things compatible with ExceptT.

but this important semantic change is not highlighted in `CHANGELOG.markdown` nor in the documentation of `bracket`. More precisely, the `release` action does not see the state updates which have been performed within the `use` action, and the code which follows `bracket acquire release use` does not see the state updates which have been performed within `release`. An example in which discarding those state updates is problematic would be a reference-counted wrapper around `bracket` which allows nested calls to `bracket` to re-use the outer `bracket`'s already allocated resource:

    {-# LANGUAGE FlexibleContexts, LambdaCase #-}
    import Control.Monad.Catch
    import Control.Monad.State

    refCountedBracket
      :: (MonadMask m, MonadState (Maybe (a, Int)) m)
      => m a -> (a -> m b) -> (a -> m c) -> m c
    refCountedBracket acquire release = bracket acquire' release'
      where
        acquire' = get >>= \case
          Nothing     -> do r <- acquire
                            put (Just (r, 1))
                            pure r
          Just (r, n) -> do put (Just (r, n+1))
                            pure r
        release' _ = get >>= \case
          Nothing     -> error "ref-counter got out of sync"
          Just (r, 1) -> do _ <- release r
                            put Nothing
          Just (r, n) -> put (Just (r, n-1))

    data Resource = UsingResource deriving Show

    withRefCountedResource
      :: (MonadIO m, MonadMask m, MonadState (Maybe (Resource, Int)) m)
      => (Resource -> m a) -> m a
    withRefCountedResource = refCountedBracket acquire release
      where
        acquire = do liftIO $ putStrLn "acquire"
                     pure UsingResource
        release UsingResource = liftIO $ putStrLn "release"

Such an implementation works fine with exceptions-0.8.3, but causes a use-after-free with exceptions-0.9.0:

    -- |
    -- With exceptions-0.8.3:
    --
    -- >>> test
    -- acquire
    -- (UsingResource,UsingResource)
    -- release
    -- acquire
    -- UsingResource
    -- release
    --
    --
    -- With exceptions-0.9.0:
    --
    -- >>> test
    -- acquire
    -- (UsingResource,UsingResource)
    -- release
    -- UsingResource
    test :: IO ()
    test = flip evalStateT Nothing $ do
      withRefCountedResource $ \r1 -> do
        withRefCountedResource $ \r2 -> do
          liftIO $ print (r1, r2)
      withRefCountedResource $ \r3 -> do
        liftIO $ print r3

With exceptions-0.8.3, everything goes as planned: the nested `r2` block sees that it is nested so it doesn't acquire nor release the resource, while the `r3` block sees that it isn't nested, so it re-acquires and re-releases the resource.

With exceptions-0.9.0, the situation is a lot more complicated. The `r1` block acquires the resource and initializes the reference counter to 1. Since this occurs during the `acquire` action, this will be visible to all the subsequent code. The nested `r2` block then increments the counter, but since the entirety of `r2` is within `r1`'s `use` action, the `release` action of `r1` won't see that change. The `release` action of `r2` does see that change, and thus chooses not to release the resource and to decrement the counter instead, but no other code will see this decrement. In particular, the `r1` block's `release` action sees neither `r2`'s increment nor its decrement, so as far as it's concerned, the reference counter is still 1 and so it releases the resource. It also sets the state to `Nothing`, but no other code will see that. In particular, the `r3` block sees all of the increments but none of the decrements, and so it thinks it is nested inside the `r2` block and does not re-acquire the resource. Inside `r3`, the resource is used again, but the resource has been freed already, so that's no good.

If this unfortunate behaviour really is required in order to give a `MonadMask` instance to `ExceptT`, would it be possible to change the type of the release block to `a -> IO c` instead of `a -> m c`, to make it more clear that we can't safely use non-IO effects within it?

### PR DESCRIPTION
**Pull request by gelisam**
I made the changes discussed in #63, added some tests, updated the documentation, and added a new `onError` method which, unlike `onException`, also runs its handler when the computation aborts which an error which is not an exception.

While we're making breaking changes, would it be worthwhile to also generalize the methods in `MonadCatch` so they can act on those non-exception errors?

### CODE REVIEW

**Comment by RyanGlScott** [comment]
I've left some comments inline. I'd definitely like @snoyberg to look over this is as well.

> While we're making breaking changes, would it be worthwhile to also generalize the methods in `MonadCatch` so they can act on those non-exception errors?

Can you be more specific on what your intent is?

File: src/Control/Monad/Catch.hs [hunk 1]
```diff
@@ -653,44 +783,56 @@ catches a hs = a `catch` handler
...
 -- | Run an action only if an exception is thrown in the main action. The
 -- exception is not caught, simply rethrown.
+--
+-- /NOTE/ The action is only run if an /exception/ is throw. If the monad
+-- supports other ways of aborting the computation, the action won't run if
+-- those other kinds of errors are thrown. See 'onError'.
 onException :: MonadCatch m => m a -> m b -> m a
 onException action handler = action `catchAll` \e -> handler >> throwM e
 
+-- | Run an action only if an error is thrown in the main action. Unlike
```
Comment (snoyberg) [inline src/Control/Monad/Catch.hs]: It may be worth spelling out that the difference is for transformers like `EitherT` and `MaybeT` that have multiple exit points.

File: src/Control/Monad/Catch.hs [hunk 2]
```diff
@@ -194,61 +214,95 @@ class MonadCatch m => MonadMask m where
...
     :: m a
     -- ^ acquire some resource
-    -> (a -> m ignored1)
-    -- ^ release, no exception thrown
-    -> (a -> SomeException -> m ignored2)
-    -- ^ release, some exception thrown; the exception will be rethrown
     -> (a -> m b)
     -- ^ inner action to perform with the resource
-    -> m b
+    -> (a -> ExitCase b -> m c)
```
Comment (snoyberg) [inline src/Control/Monad/Catch.hs]: I should have commented on this earlier. I think it would make more sense to move the release action to before the use action, to match more closely the type signature of `bracket` in `base`.

File: src/Control/Monad/Catch.hs [hunk 3]
```diff
@@ -178,14 +199,13 @@ class MonadCatch m => MonadMask m where
...
-  -- distinguishing different exit cases. Instead of providing it a single
-  -- release action, this function takes two different actions: one for the
-  -- case of a successful run of the inner function, and one in the case of an
-  -- exception. The former function is provided the acquired value, while
-  -- the exception release function is provided both the acquired value and
-  -- the exception that was thrown. The result values of both of these
-  -- functions are ignored.
+  -- | A generalized version of 'bracket' which uses 'ExitCase' to distinguish
+  -- the different exit cases, and returns the values of both the 'use' and
+  -- 'release' actions. You should probably use 'bracket' instead.
```
Comment (snoyberg) [inline src/Control/Monad/Catch.hs]: I'd probably clarify _why_ `bracket` is better to use (more ergonomic), and comment that many other functions (like `finally`) are built on top of this method.

File: src/Control/Monad/Catch.hs [hunk 4]
```diff
@@ -194,61 +214,95 @@ class MonadCatch m => MonadMask m where
...
-    -> (a -> m ignored1)
-    -- ^ release, no exception thrown
-    -> (a -> SomeException -> m ignored2)
-    -- ^ release, some exception thrown; the exception will be rethrown
     -> (a -> m b)
     -- ^ inner action to perform with the resource
-    -> m b
+    -> (a -> ExitCase b -> m c)
+    -- ^ release the resource, observing the outcome of the inner action
+    -> m (b, c)
```
Comment (snoyberg) [inline src/Control/Monad/Catch.hs]: I think this signature makes things much easier to understand.

**Comment by gelisam** [comment]
>> While we're making breaking changes, would it be worthwhile to also generalize the methods in `MonadCatch` so they can act on those non-exception errors?
> 
> Can you be more specific on what your intent is?

With `MonadMask`, we can now handle two kinds of error cases: `ExitCaseException` and `ExitCaseAbort`. `MonadCatch` can only handle the `ExitCaseException` case. I thought it might be more consistent if `MonadCatch` was also extended to support both cases, by adding a method which could look like this, with `Nothing` representing the `ExitCaseAbort` case:

    generalCatch :: Exception e => m a -> (Maybe e -> m a) -> m a

But now that I'm thinking about this more, I don't think it makes a lot of sense to add a variant to the `catch` and `handle` family of functions which can catch the `ExitCaseAbort` case, because we don't have a concrete value to give to this handler. The user would be better-served by a monad-specific catching function like [`catchE`](https://hackage.haskell.org/package/transformers-0.5.5.0/docs/Control-Monad-Trans-Except.html#v:catchE).

**Comment by gelisam** [comment]
> I'm not exactly sure what form your suggestion is going to take on

To clarify: I no longer have a suggestion for changing `MonadCatch`; I had one but I have retracted it.

**Comment by gelisam** [comment]
I have now addressed all the inline comments. I have also added the an entry to the changelog about the new `onError` function, added comments around the `StateT` and `ExceptT` implementations as a reminder to keep the documentation's copy of their implementation in sync, and I have added a few more `@since` annotations.

File: src/Control/Monad/Catch.hs [hunk 5]
```diff
@@ -653,44 +796,61 @@ catches a hs = a `catch` handler
...
+-- those other kinds of errors are thrown. See 'onError'.
 onException :: MonadCatch m => m a -> m b -> m a
 onException action handler = action `catchAll` \e -> handler >> throwM e
 
+-- | Run an action only if an error is thrown in the main action. Unlike
+-- 'onException', this works with every kind of error, not just exceptions. For
+-- example, if @f@ is an 'ExceptT' computation which aborts with a 'Left', the
+-- computation @onError f g@ will execute @g@, while @onException f g@ will not.
+--
+-- For monads which, unlike 'ExceptT' and 'MaybeT', only have a single exit
```
Comment (RyanGlScott) [inline src/Control/Monad/Catch.hs]: The phrasing of this sentence is a little awkward. I would prefer stating it like:

"This distinction is only meaningful for monads which have multiple exit points, such as 'Except' and 'MaybeT'. For monads that only have a single exit point, there is no difference between 'onException' and 'onError', except that 'onError' has a more constrained type."

File: src/Control/Monad/Catch.hs [hunk 6]
```diff
@@ -194,61 +217,97 @@ class MonadCatch m => MonadMask m where
...
-    -> (a -> m ignored1)
-    -- ^ release, no exception thrown
-    -> (a -> SomeException -> m ignored2)
-    -- ^ release, some exception thrown; the exception will be rethrown
+    -> (a -> ExitCase b -> m c)
+    -- ^ release the resource, observing the outcome of the inner action
     -> (a -> m b)
     -- ^ inner action to perform with the resource
-    -> m b
+    -> m (b, c)
```
Comment (RyanGlScott) [inline src/Control/Monad/Catch.hs]: How do we feel about the order of type variables in `generalBracket`? Our primary motivator for picking this order of arguments was to match what `bracket` does, but now we have:

```haskell
bracket
  :: IO a
  -> (a -> IO b)
  -> (a -> IO c)
  -> IO c

generalBracket
  :: m a
  -> (a -> ExitCase b -> m c)
  -> (a -> m b)
  -> m (b, c)
```

Now, the type variables `b` and `c` are in the opposite order as in `bracket`. We could conceivably change this to:

```haskell
generalBracket
  :: m a
  -> (a -> ExitCase c -> m b)
  -> (a -> m c)
  -> m (b, c)
```

Or even:

```haskell
generalBracket
  :: m a
  -> (a -> ExitCase c -> m b)
  -> (a -> m c)
  -> m (c, b)
```

I don't have a strong opinion one way or the other. Thoughts?

Comment (gelisam) [reply src/Control/Monad/Catch.hs]: I don't have a strong opinion either. I'll change it to your first suggestion in order to at least match bracket's `(a -> m c)`, then change it back if someone feels strongly about this :)

Comment (RyanGlScott) [reply src/Control/Monad/Catch.hs]: OK. The return type is interesting because it might hint at an order of evaluation. That is, the action which returns `c` runs before the action which returns `b`, hence `m (c, b)`. On the other hand, this puts us back into a state where the type variables are out-of-order again. Perhaps the order of evaluation is already obvious because `ExitCase c` appears as an argument to the function which returns an `m b`?

Comment (gelisam) [reply src/Control/Monad/Catch.hs]: Now that I am attempting the change, I feel like changing the variable names is a bad idea. It's important to thread the state in the correct order: from acquire to use, then from use to release. By swapping the order of `use` and `release` to match `bracket`, we have already made it less obvious that this is what implementors need to do. Let's at least keep these variable names as is in order to give a hint of the right ordering.

Comment (gelisam) [reply src/Control/Monad/Catch.hs]: Would it be crazy to change change the type variables in `bracket` to match `generalBracket`, to make it clearer that even though `use` is last so `bracket` curries better, it is executed in the middle of the `a` and `c` bits?

    bracket
     :: IO a
      -> (a -> IO c)
      -> (a -> IO b)
      -> IO b

Comment (RyanGlScott) [reply src/Control/Monad/Catch.hs]: That sounds like a reasonable suggestion too (short of actually swapping the order of those arguments).

**Comment by RyanGlScott** [comment]
Looking good! At this point, the only issue is that this doesn't build on old GHCs due to `<$>` and `<*>` not being in scope. I think you can fix both of these issues with:

```haskell
import Control.Applicative
```

At around line 106 or so (within the `#elif __GLASGOW_HASKELL__ < 710 ... #endif` CPP).

File: src/Control/Monad/Catch.hs (hunk 6 above)
Comment (gelisam) [reply src/Control/Monad/Catch.hs]: done

**Comment by RyanGlScott** [comment]
So close :)

Travis is now complaining:

```
src/Control/Monad/Catch.hs:835:27:
    Could not deduce (Functor m) arising from a use of ‘fmap’
    from the context (MonadMask m)
      bound by the type signature for
                 bracket :: MonadMask m => m a -> (a -> m c) -> (a -> m b) -> m b
      at src/Control/Monad/Catch.hs:834:12-64
    Possible fix:
      add (Functor m) to the context of
        the type signature for
          bracket :: MonadMask m => m a -> (a -> m c) -> (a -> m b) -> m b
    In the first argument of ‘(.)’, namely ‘fmap fst’
    In the expression:
      fmap fst . generalBracket acquire (\ a _exitCase -> release a)
    In an equation for ‘bracket’:
        bracket acquire release
          = fmap fst . generalBracket acquire (\ a _exitCase -> release a)

src/Control/Monad/Catch.hs:852:34:
    Could not deduce (Functor m) arising from a use of ‘fmap’
    from the context (MonadMask m)
      bound by the type signature for
                 bracketOnError :: MonadMask m =>
                                   m a -> (a -> m c) -> (a -> m b) -> m b
      at src/Control/Monad/Catch.hs:851:19-71
    Possible fix:
      add (Functor m) to the context of
        the type signature for
          bracketOnError :: MonadMask m =>
                            m a -> (a -> m c) -> (a -> m b) -> m b
    In the first argument of ‘(.)’, namely ‘fmap fst’
    In the expression:
      fmap fst
      . generalBracket
          acquire
          (\ a exitCase
             -> case exitCase of {
                  ExitCaseSuccess _ -> return ()
                  _ -> do { _ <- release a;
                            .... } })
    In an equation for ‘bracketOnError’:
        bracketOnError acquire release
          = fmap fst
            . generalBracket
                acquire
                (\ a exitCase
                   -> case exitCase of {
                        ExitCaseSuccess _ -> return ()
                        _ -> do { ... } })
```

I think replacing these uses of `fmap` with `liftM` will do the trick.

**Comment by RyanGlScott** [comment]
Oh, right. Currently, the `Control.Applicative` import is only in scope _between_ GHC 7.6 and 7.10, which is why it's now only failing on GHC 7.4. Try taking out that import and putting it in its own:

```haskell
#if __GLASGOW_HASKELL__ < 710
import Control.Applicative
#endif
```

**Comment by gelisam** [comment]
Slowly but surely!

**Comment by RyanGlScott** [comment]
Thanks, @gelisam! I'll try to get a new release out next week.
